service: elasticache-example
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2
  iam:
    role:
      managedPolicies:
        - "arn:aws:iam::aws:policy/AmazonElastiCacheFullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"

functions:
  writeCache:
    handler: index.handler
    environment:
      REDIS_PORT: !GetAtt MyElasticacheCluster.RedisEndpoint.Port
      REDIS_HOST: !GetAtt MyElasticacheCluster.RedisEndpoint.Address
    events:
      - httpApi: POST /write-cache
    vpc:
      securityGroupIds:
        - !GetAtt MyLambdaSecurityGroup.GroupId
      subnetIds:
        - !Ref MySubnet

resources:
  Resources:
    MyVPC:
      Type: "AWS::EC2::VPC"
      Properties:
        CidrBlock: "10.0.0.0/16"

    MySubnet:
      Type: "AWS::EC2::Subnet"
      Properties:
        VpcId: !Ref MyVPC
        CidrBlock: "10.0.1.0/24"

    MyLambdaSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: "Lambda function security group"
        VpcId: !Ref MyVPC

    MyElasticacheSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: "ElastiCache security group"
        VpcId: !Ref MyVPC
        SecurityGroupIngress:
          - IpProtocol: "tcp" # Specify TCP protocol
            FromPort: "6379" # Port 6379
            ToPort: "6379" # Port 6379
            CidrIp: "10.0.1.0/24"

    MyElasticacheSubnetGroup:
      Type: "AWS::ElastiCache::SubnetGroup"
      Properties:
        Description: "Subnet Group for ElastiCache"
        SubnetIds:
          - !Ref MySubnet
        CacheSubnetGroupName: "MyElasticacheSubnetGroupNew"

    MyElasticacheCluster:
      Type: "AWS::ElastiCache::CacheCluster"
      Properties:
        CacheNodeType: "cache.t2.micro"
        Engine: "redis"
        NumCacheNodes: "1"
        CacheSubnetGroupName: !Ref MyElasticacheSubnetGroup
        VpcSecurityGroupIds:
          - !GetAtt MyElasticacheSecurityGroup.GroupId